name: Release

on:
  #push:
  #  tags:
  #    - '*'
  pull_request:
    branches: [ master, main ]

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup fpm
        run: |
          gem install --no-document fpm

      #- name: Run GoReleaser
      #  uses: goreleaser/goreleaser-action@v2
      #  with:
      #    distribution: goreleaser
      #    version: v0.169.0
      #    args: release --rm-dist
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
